CREATE DATABASE IF NOT EXISTS laravel;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON laravel.* TO 'user'@'%';

CREATE USER IF NOT EXISTS 'user'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON laravel.* TO 'user'@'localhost';

FLUSH PRIVILEGES;
